name: Run Python Script
    
on:
  push:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Download Weight File
      run: |
        python download.py "https://drive.google.com/open?id=1Jk4eGD7crsqCCg9C9VjCLkMN3ze8kutZ" weightfile.pth
    
    - name: Run Script
      run: |
        python test.py --trained_model=weightfile.pth --test_folder=test_images